[libraries]
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4j" }

[plugins]
dependencyCheck = { id = "org.owasp.dependencycheck", version.ref = "dependencyCheckPlugin" }
jmh = { id = "me.champeau.jmh", version.ref = "jmhPlugin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }

[versions]
dependencyCheckPlugin = "12.2.0"
icu4j = "78.2"
jmhPlugin = "0.7.3"
lombokPlugin = "9.1.0"
versionsPlugin = "0.53.0"
