[libraries]
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4j" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
jmh = { id = "me.champeau.jmh", version.ref = "jmhPlugin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }

[versions]
icu4j = "73.1"
jmhPlugin = "0.7.1"
junit = "5.9.3"
lombokPlugin = "8.0.1"
versionsPlugin = "0.46.0"
